import type { CefrLevel } from "./question-bank"
import type { TopicDef } from "./topics"

const API_BASE = "https://generativelanguage.googleapis.com/v1beta"

/** Cheap, fast model for bulk exercise generation. Override with GEMINI_EXERCISE_MODEL. */
export const EXERCISE_MODEL = process.env.GEMINI_EXERCISE_MODEL ?? "gemini-3.5-flash-lite"
/** More capable model reserved for heavier generation tasks (e.g. future topic authoring). */
export const HEAVY_MODEL = process.env.GEMINI_HEAVY_MODEL ?? "gemini-3.7-flash"

/**
 * Bump whenever the exercise prompt changes so cached rows generated by the
 * old prompt are naturally bypassed by new cache keys.
 */
export const PROMPT_VERSION = "v1"

export type GeneratedExercise = {
  word: string
  cefr: string
  spanish_translation: string
  phonetic: string
  example_sentence: string
  exercise: {
    type: string
    question: string
    options: string[]
    answer: string
  }
}

function requireApiKey() {
  const key = process.env.GEMINI_API_KEY
  if (!key) throw new Error("GEMINI_API_KEY is not configured")
  return key
}

type GeminiResponse = {
  candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>
  error?: { message?: string }
}

const RESPONSE_SCHEMA = {
  type: "ARRAY",
  items: {
    type: "OBJECT",
    properties: {
      word: { type: "STRING" },
      cefr: { type: "STRING" },
      spanish_translation: { type: "STRING" },
      phonetic: { type: "STRING" },
      example_sentence: { type: "STRING" },
      exercise: {
        type: "OBJECT",
        properties: {
          type: { type: "STRING" },
          question: { type: "STRING" },
          options: { type: "ARRAY", items: { type: "STRING" } },
          answer: { type: "STRING" },
        },
        required: ["type", "question", "options", "answer"],
      },
    },
    required: ["word", "cefr", "spanish_translation", "phonetic", "example_sentence", "exercise"],
  },
} as const

function buildPrompt(
  words: Array<{ english: string; spanish: string }>,
  levelId: CefrLevel,
  levelCode: string,
  topic: TopicDef,
): string {
  return [
    `You are an expert Cambridge English exam content writer.`,
    ``,
    `Create ONE multiple-choice vocabulary exercise for EACH word in the list below.`,
    `Target level: CEFR ${levelCode} (${levelId}).`,
    `Topic: ${topic.title}. Sentence context must reflect this focus: ${topic.focus}`,
    ``,
    `For every input word return an object with:`,
    `- "word": exactly the given English word.`,
    `- "cefr": "${levelCode}".`,
    `- "spanish_translation": the provided Spanish translation, unchanged.`,
    `- "phonetic": IPA transcription of the word, like /ˈtʃæl.ɪndʒ/.`,
    `- "example_sentence": one natural sentence at CEFR ${levelCode} using the word, matching the topic focus.`,
    `- "exercise.type": "fill_in_the_blank".`,
    `- "exercise.question": the example sentence with the word replaced by "______".`,
    `- "exercise.options": EXACTLY 3 strings — the correct word plus 2 plausible distractors with similar length and register but clearly wrong meaning or form.`,
    `- "exercise.answer": exactly the correct word (must equal "word").`,
    ``,
    `Input words (JSON): ${JSON.stringify(words)}`,
    ``,
    `Return ONLY a JSON array containing one object per input word, in the same order.`,
  ].join("\n")
}

async function callGemini(prompt: string, model: string): Promise<unknown> {
  const key = requireApiKey()
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 60_000)
  try {
    const response = await fetch(`${API_BASE}/models/${model}:generateContent?key=${key}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.7,
          responseMimeType: "application/json",
          responseSchema: RESPONSE_SCHEMA,
        },
      }),
      signal: controller.signal,
    })
    const data = (await response.json()) as GeminiResponse
    if (!response.ok) throw new Error(data.error?.message ?? `Gemini API error (${response.status})`)
    const text = data.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("") ?? ""
    if (!text) throw new Error("Gemini returned an empty response")
    return JSON.parse(text)
  } finally {
    clearTimeout(timeout)
  }
}

function validate(raw: unknown, expectedWords: string[]): GeneratedExercise[] {
  if (!Array.isArray(raw)) throw new Error("Gemini response is not a JSON array")
  const expected = new Set(expectedWords.map((word) => word.toLowerCase()))
  const results: GeneratedExercise[] = []
  for (const item of raw) {
    const candidate = item as Partial<GeneratedExercise>
    const word = candidate.word?.trim()
    const exercise = candidate.exercise
    if (
      !word ||
      !expected.has(word.toLowerCase()) ||
      !candidate.cefr ||
      typeof candidate.spanish_translation !== "string" ||
      typeof candidate.phonetic !== "string" ||
      typeof candidate.example_sentence !== "string" ||
      !exercise ||
      typeof exercise.question !== "string" ||
      !exercise.question.includes("______") ||
      !Array.isArray(exercise.options) ||
      exercise.options.length < 2 ||
      typeof exercise.answer !== "string" ||
      !exercise.options.includes(exercise.answer)
    ) {
      continue
    }
    results.push({
      word,
      cefr: candidate.cefr,
      spanish_translation: candidate.spanish_translation,
      phonetic: candidate.phonetic,
      example_sentence: candidate.example_sentence,
      exercise: {
        type: exercise.type || "fill_in_the_blank",
        question: exercise.question,
        options: exercise.options.map((option) => String(option)),
        answer: exercise.answer,
      },
    })
  }
  return results
}

/**
 * Generates exercises for the given words in a single Gemini call.
 * Retries once on failure; returns whatever items passed validation.
 */
export async function generateExercises(
  words: Array<{ english: string; spanish: string }>,
  levelId: CefrLevel,
  levelCode: string,
  topic: TopicDef,
): Promise<GeneratedExercise[]> {
  const model = EXERCISE_MODEL
  const prompt = buildPrompt(words, levelId, levelCode, topic)
  let lastError: unknown
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const raw = await callGemini(prompt, model)
      const parsed = validate(raw, words.map((word) => word.english))
      if (parsed.length > 0) return parsed
      lastError = new Error("All generated exercises failed validation")
    } catch (error) {
      lastError = error
    }
  }
  throw lastError instanceof Error ? lastError : new Error("Exercise generation failed")
}
